name: Self-Hosted Runner Test

on:
  workflow_dispatch:

jobs:
  test-runner:
    runs-on: [self-hosted, ARM64]
    steps:
      - name: âœ… æ‰“å°ä¸»æœºå
        run: hostname

      - name: ğŸ§ æŸ¥çœ‹ç³»ç»Ÿä¿¡æ¯
        run: uname -a

      - name: ğŸ“‚ æŸ¥çœ‹å½“å‰ç›®å½•
        run: ls -alh
